#!/bin/sh
#
# Saumon i3blocks scripts : load
# (1 minute load with colors)
#

nproc=$(nproc)
warningPercent=$(echo "$nproc * 65" | bc -l | tr -d '\n')
criticalPercent=$(echo "$nproc * 90" | bc -l | tr -d '\n')

load=$(cut -d ' ' -f1 /proc/loadavg | tr -d '\n')
loadPercent=$(echo "$load * 100" | bc -l | xargs printf "%.0f")
avgLoadPercent=$(echo "$load * 100 / $nproc" | bc -l | xargs printf "%.0f%")

if [ "$loadPercent" -ge "$criticalPercent" ]; then
  color="#f44336"
elif [ "$loadPercent" -ge "$warningPercent" ]; then
  color="#ff9800"
else
  color="$COLOR"
fi

printf "<span color='%s'></span> %s%%\n" "$color" "$avgLoadPercent"
