#!/bin/bash

# Copyright (C) 2020 Pavel Makhov <streetturtle@gmail.com>


case $BLOCK_BUTTON in
    1) sp play ;; # left click
    4) sp next ;; # scroll up
    5) sp prev ;; # scroll down
esac

if sp status | grep 'Paused' > /dev/null; then
	st='<span color=\"coral\"><\/span>' # fa-pause
elif sp status | grep 'Playing' > /dev/null; then
	st='<span color=\"coral\"><\/span>' # fa-play
else
    echo ""
    die
fi
sp current-oneline | sed "s/\&/&amp;/g" | sed "s/ [|] / $st /g"

