#!/usr/bin/env bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------
if [[ -z "$INTERFACE" ]] ; then
    IFS=, read WLAN_INTERFACE ETH_INTERFACE <<< ${BLOCK_INSTANCE:-wlan0,eth0}
fi
#------------------------------------------------------------------------

#COLOR_GE80=${COLOR_GE80:-#00FF00}
#COLOR_GE60=${COLOR_GE60:-#FFF600}
#COLOR_GE40=${COLOR_GE40:-#FFAE00}
#COLOR_LOWR=${COLOR_LOWR:-#FF0000}
#COLOR_DOWN=${COLOR_DOWN:-#FF0000}

COLOR_GE80=${COLOR_GE80:-#FF7F50}
COLOR_GE60=${COLOR_GE60:-#FF7F50}
COLOR_GE40=${COLOR_GE40:-#FF7F50}
COLOR_LOWR=${COLOR_LOWR:-#FF7F50}
COLOR_DOWN=${COLOR_DOWN:-#FF7F50}

case $BLOCK_BUTTON in
    1|2)
        nmcli-rofi
        ;;
esac

ETH_INTERFACES="enp0s31f6|enx186571ed38c7"

ETHERNET_CONNECTED=$(ip a | grep -E -o -m 1 "($ETH_INTERFACES):.*state UP")
if [[ ! -z $ETHERNET_CONNECTED ]]; then
    echo ""
    echo ""
    echo $COLOR_GE80
    exit
fi

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${WLAN_INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$WLAN_INTERFACE/operstate)" = 'down' ]]; then
    echo ""
    echo ""
    echo $COLOR_DOWN
    exit
fi

#------------------------------------------------------------------------

QUALITY=$(iw dev ${WLAN_INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

#------------------------------------------------------------------------

# color
if [[ $QUALITY -ge 80 ]]; then
    ICON=""
elif [[ $QUALITY -ge 60 ]]; then
    ICON=""
elif [[ $QUALITY -ge 40 ]]; then
    ICON=""
else
    ICON=""
fi

echo "<span color='coral'>$ICON</span> $QUALITY%" # full text
echo "<span color='coral'>$ICON</span> $QUALITY%" # short text
